### PR TITLE
Update to Unicode 11.0 [breaking change].

### PR DESCRIPTION
**Pull request by mbrubeck**
This is a breaking change because the variants of the public `Script` enum have changed.  Code that matches this enum exhaustively must be updated.

Depends on servo/rust-harfbuzz#78.

### CODE REVIEW

**Comment by behnam** [comment]
Script property is a Unicode Catalog type and expected to change on every single Unicode release.

How about we mark the Enum as open now, so we don't have to call it breaking because of this again?

**Comment by apendleton** [comment]
11.0 is out now, so may as well skip straight to that? http://unicode.org/versions/Unicode11.0.0/

**Comment by pcwalton** [comment]
Agreed with @behnam.

**Comment by mbrubeck** [comment]
Updated to Unicode 11.0 and made the enum open.

Note: The harfbuzz-sys crate hasn't yet been updated to a version of Harfbuzz that includes Unicode 11.0.  Once it is, this can be updated to support the new HB_SCRIPT constants.

**Comment by RazrFalcon** [comment]
Version 12 available.

**Pull request closed without merging**
